#App config
spring.application.name=TechInterview-AI
server.port=8989

#DB Configuration
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

#JWT Configuration
hajar.app.jwtSecret=${JWT_SECRET}
hajar.app.jwtExpirationMs=${JWT_EXPIRATION}

# Spring AI : pointing to Gradient AI endpoint
spring.ai.openai.base-url=https://inference.do-ai.run
spring.ai.openai.api-key=${GRADIENT_MODEL_ACCESS_KEY}


app.cors.allowed-origins=https://ai-technical-interview-simulator-hkbxr.ondigitalocean.app

app.interview.max-questions=8
